// flow-typed signature: 1932a49479a06ed0af538391abd190bc
// flow-typed version: <<STUB>>/rust-keywords_v1.0.1/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rust-keywords'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rust-keywords' {
  declare module.exports: Array<string>;
}
