// import { numberTypeAnnotation } from "@babel/types/lib/builders/generated";

// flow-typed signature: 29daf43d438bce142dd0df073cf3d87d
// flow-typed version: <<STUB>>/@babel/types_v7.0.0-beta.35/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/types' {
  declare module.exports: any;
}
